version: "3.1"

services:
  database:
    container_name: database
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data:
