CREATE TYPE TRANSACTION_CLASS AS ENUM('FRAUDULENT', 'GENUINE');

CREATE TABLE transactions (
    -- Problem attributes
    time INTEGER NOT NULL,
    v1 DECIMAL NOT NULL,
    v2 DECIMAL NOT NULL,
    v3 DECIMAL NOT NULL,
    v4 DECIMAL NOT NULL,
    v5 DECIMAL NOT NULL,
    v6 DECIMAL NOT NULL,
    v7 DECIMAL NOT NULL,
    v8 DECIMAL NOT NULL,
    v9 DECIMAL NOT NULL,
    v10 DECIMAL NOT NULL,
    v11 DECIMAL NOT NULL,
    v12 DECIMAL NOT NULL,
    v13 DECIMAL NOT NULL,
    v14 DECIMAL NOT NULL,
    v15 DECIMAL NOT NULL,
    v16 DECIMAL NOT NULL,
    v17 DECIMAL NOT NULL,
    v18 DECIMAL NOT NULL,
    v19 DECIMAL NOT NULL,
    v20 DECIMAL NOT NULL,
    v21 DECIMAL NOT NULL,
    v22 DECIMAL NOT NULL,
    v23 DECIMAL NOT NULL,
    v24 DECIMAL NOT NULL,
    v25 DECIMAL NOT NULL,
    v26 DECIMAL NOT NULL,
    v27 DECIMAL NOT NULL,
    v28 DECIMAL NOT NULL,
    amount DECIMAL NOT NULL,
    class TRANSACTION_CLASS,

    -- Meta attributes
    id UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),

    PRIMARY KEY(id)
);
